Make build fail early

diff --git a/platform/build b/platform/build
--- a/platform/build
+++ b/platform/build
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# exit when any command fails
+set -e
+
 SOURCE_DIR=/tmp/source
 
 if [[ $1 = "server" ]] || [[ $1 = "all" ]]; then
